import React, { useState } from 'react';
import { Clock, ChevronLeft, ChevronRight, User, Plus, Trash2 } from 'lucide-react';
import { useStore, store } from '../../lib/store';
import Button from '../ui/Button';
import { toast } from 'react-hot-toast';

const DAYS = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'];

const ShiftCalendar: React.FC = () => {
  const { shifts } = useStore();
  const [currentWeek] = useState(1);
  const [showAddModal, setShowAddModal] = useState(false);
  const [newShift, setNewShift] = useState({ staffName: '', day: 0, start: '09:00', end: '17:00' });

  const handleAddShift = () => {
      if (!newShift.staffName) return;
      // Calculate date based on day index (mock logic)
      const date = `2024-02-${20 + newShift.day}`; 
      
      store.addShift({
          id: Math.random().toString(36).substr(2, 5),
          staffId: 'temp-' + Date.now(),
          staffName: newShift.staffName,
          date: date,
          start: newShift.start,
          end: newShift.end,
          role: 'Staff',
          isAutoGenerated: false
      });
      setShowAddModal(false);
      setNewShift({ staffName: '', day: 0, start: '09:00', end: '17:00' });
      toast.success('Shift Added');
  };

  const deleteShift = (id: string, e: React.MouseEvent) => {
      e.stopPropagation();
      if (confirm('Remove this shift?')) {
          store.deleteShift(id);
          toast.success('Shift Removed');
      }
  };

  return (
    <div className="space-y-6">
      <div className="flex justify-between items-center">
        <h2 className="text-2xl font-bold text-white font-serif">Staff Schedule</h2>
        <div className="flex gap-4">
            <Button onClick={() => setShowAddModal(true)}><Plus size={16} className="mr-2"/> Add Shift</Button>
            <div className="flex items-center gap-4 bg-[#1a1a1a] p-2 rounded-lg border border-white/10">
                <button className="p-1 hover:text-white text-white/60"><ChevronLeft size={20}/></button>
                <span className="font-mono text-sm">Week {currentWeek}, Feb 2024</span>
                <button className="p-1 hover:text-white text-white/60"><ChevronRight size={20}/></button>
            </div>
        </div>
      </div>

      {showAddModal && (
          <div className="fixed inset-0 bg-black/80 backdrop-blur-sm z-50 flex items-center justify-center p-4">
              <div className="bg-[#1a1a1a] p-6 rounded-xl border border-white/10 w-full max-w-md space-y-4">
                  <h3 className="text-xl font-bold text-white">Add New Shift</h3>
                  
                  <div>
                      <label className="text-xs text-zinc-400 block mb-1">Staff Name</label>
                      <input className="w-full bg-black border border-white/10 rounded p-2 text-white" 
                           value={newShift.staffName} onChange={e => setNewShift({...newShift, staffName: e.target.value})} placeholder="e.g. Sarah"/>
                  </div>
                  <div>
                      <label className="text-xs text-zinc-400 block mb-1">Day</label>
                      <select className="w-full bg-black border border-white/10 rounded p-2 text-white"
                           value={newShift.day} onChange={e => setNewShift({...newShift, day: Number(e.target.value)})}>
                          {DAYS.map((d, i) => <option key={d} value={i}>{d}</option>)}
                      </select>
                  </div>
                  <div className="flex gap-4">
                      <div className="flex-1">
                          <label className="text-xs text-zinc-400 block mb-1">Start</label>
                          <input type="time" className="w-full bg-black border border-white/10 rounded p-2 text-white" 
                               value={newShift.start} onChange={e => setNewShift({...newShift, start: e.target.value})}/>
                      </div>
                      <div className="flex-1">
                          <label className="text-xs text-zinc-400 block mb-1">End</label>
                          <input type="time" className="w-full bg-black border border-white/10 rounded p-2 text-white" 
                               value={newShift.end} onChange={e => setNewShift({...newShift, end: e.target.value})}/>
                      </div>
                  </div>

                  <div className="flex gap-2 pt-2">
                       <Button onClick={handleAddShift} className="flex-1">Add Shift</Button>
                       <Button onClick={() => setShowAddModal(false)} variant="outline" className="flex-1">Cancel</Button>
                  </div>
              </div>
          </div>
      )}

      <div className="grid grid-cols-7 gap-px bg-white/10 rounded-xl overflow-hidden border border-white/10 shadow-lg">
          {DAYS.map((day, i) => (
              <div key={day} className="bg-[#121212] min-h-[300px] p-3 flex flex-col">
                  <div className="text-center mb-4 pb-2 border-b border-white/5">
                      <span className="text-xs uppercase tracking-widest text-white/40 font-bold">{day}</span>
                      <div className="text-xl font-serif text-white mt-1">{20 + i}</div>
                  </div>
                  
                  <div className="space-y-2 flex-1 relative">
                       {shifts.map((shift) => {
                           // Mock date matching logic for demo (since date strings are arbitrary)
                           // Check if shift date corresponds to this day index
                           // Just a simple hack for the demo to distribute shifts
                           const shiftDay = new Date(shift.date).getDate(); // e.g. 20
                           // Compare with current cell date (20 + i)
                           if (shiftDay !== (20 + i)) return null;

                           return (
                               <div key={shift.id} className="group p-2 rounded text-xs border-l-2 custom-shift-card bg-white/5 border-primary text-white relative hover:bg-white/10 transition-colors cursor-pointer">
                                   <button onClick={(e) => deleteShift(shift.id, e)} className="absolute top-1 right-1 opacity-0 group-hover:opacity-100 text-zinc-400 hover:text-red-400"><Trash2 size={10}/></button>
                                   <div className="font-bold mb-1 flex items-center gap-1"><User size={10}/> {shift.staffName}</div>
                                   <div className="flex items-center gap-1 opacity-70 font-mono"><Clock size={10}/> {shift.start}-{shift.end}</div>
                               </div>
                           );
                       })}
                       {shifts.filter(s => new Date(s.date).getDate() === (20+i)).length === 0 && (
                           <div className="absolute inset-0 flex items-center justify-center text-white/10 text-[10px] italic pointer-events-none">Free</div>
                       )}
                  </div>
              </div>
          ))}
      </div>
    </div>
  );
};

export default ShiftCalendar;
