import React, { useState } from 'react';
import { Users, Sparkles, Calendar, Trash2, Plus } from 'lucide-react';
import { type RosterShift } from '../../types';
import Button from '../ui/Button';
import { toast } from 'react-hot-toast';

const MOCK_SHIFTS: RosterShift[] = [
  { id: '1', staffId: 's1', staffName: 'Gordon R.', date: '2024-03-20', start: '10:00', end: '16:00', role: 'Chef', isAutoGenerated: true },
  { id: '2', staffId: 's2', staffName: 'Marco P.', date: '2024-03-20', start: '16:00', end: '22:00', role: 'Chef', isAutoGenerated: true },
  { id: '3', staffId: 's3', staffName: 'Julia C.', date: '2024-03-20', start: '11:00', end: '23:00', role: 'Server', isAutoGenerated: false },
];

const SmartRoster: React.FC = () => {
  const [shifts, setShifts] = useState<RosterShift[]>(MOCK_SHIFTS);

  const generateRoster = () => {
    // Simulate AI generation delay
    const toastId = toast.loading('AI Analyzing Forecast & Staff Availability...');
    
    setTimeout(() => {
        const newShifts: RosterShift[] = [
            {
                id: Date.now().toString(),
                staffId: 's4',
                staffName: 'AI Pick: Sarah L.',
                date: '2024-03-20',
                start: '12:00',
                end: '20:00',
                role: 'Runner',
                isAutoGenerated: true
            },
            {
                id: (Date.now() + 1).toString(),
                staffId: 's5',
                staffName: 'AI Pick: Mike T.',
                date: '2024-03-20',
                start: '17:00',
                end: '23:00',
                role: 'Bartender',
                isAutoGenerated: true
            }
        ];
        setShifts([...shifts, ...newShifts]);
        toast.success('Roster Generated Successfully!', { id: toastId });
    }, 1500);
  };

  const deleteShift = (id: string) => {
      setShifts(shifts.filter(s => s.id !== id));
      toast.success('Shift Removed');
  };

  return (
    <div className="space-y-6">
       <div className="flex items-center justify-between">
         <h2 className="text-xl font-bold text-white flex items-center gap-2"><Users /> Smart Roster</h2>
         <div className="flex gap-2">
            <Button variant="outline"><Plus size={16} className="mr-2"/> Manual Add</Button>
            <Button onClick={generateRoster} className="bg-purple-600 hover:bg-purple-700 border-none animate-shimmer bg-[linear-gradient(110deg,#9333ea,45%,#a855f7,55%,#9333ea)] bg-[length:200%_100%] transition-colors">
                <Sparkles size={16} className="mr-2" /> Auto-Generate
            </Button>
         </div>
      </div>

      <div className="bg-[#1a1a1a] rounded-xl border border-white/10 overflow-hidden">
        <div className="p-4 bg-white/5 border-b border-white/5 flex gap-4">
             <div className="flex items-center gap-2 text-zinc-400">
                <Calendar size={16} /> March 20, 2024
             </div>
        </div>
        <div className="divide-y divide-white/5">
            {shifts.map(shift => (
                <div key={shift.id} className="p-4 flex items-center justify-between hover:bg-white/5 transition group">
                    <div className="flex items-center gap-4">
                        <div className={`w-10 h-10 rounded-full flex items-center justify-center font-bold text-black border-2 border-transparent group-hover:border-white/20 transition ${shift.role === 'Chef' ? 'bg-orange-400' : 'bg-blue-400'}`}>
                            {shift.staffName.charAt(0)}
                        </div>
                        <div>
                            <div className="text-white font-medium flex items-center gap-2">
                                {shift.staffName}
                                {shift.isAutoGenerated && (
                                    <span className="text-[10px] bg-purple-500/20 text-purple-300 px-1.5 py-0.5 rounded flex items-center gap-1 border border-purple-500/30">
                                        <Sparkles size={8} /> AI
                                    </span>
                                )}
                            </div>
                            <div className="text-zinc-500 text-xs">{shift.role}</div>
                        </div>
                    </div>
                    <div className="flex items-center gap-4">
                        <div className="bg-black/40 px-3 py-1 rounded text-sm text-zinc-300 font-mono border border-white/5">
                            {shift.start} - {shift.end}
                        </div>
                        <button onClick={() => deleteShift(shift.id)} className="text-zinc-600 hover:text-red-400 transition p-2">
                            <Trash2 size={16} />
                        </button>
                    </div>
                </div>
            ))}
            {shifts.length === 0 && (
                <div className="p-8 text-center text-zinc-500 italic">No shifts scheduled. Click Auto-Generate to populate based on forecast.</div>
            )}
        </div>
      </div>
    </div>
  );
};

export default SmartRoster;
